language: rust

matrix:
  include:
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly

cache: cargo

before_install:
  - set -e
  - rustup self update

install:
  - rustup target add $TARGET || true

script:
  - cargo check --target $TARGET
  - cargo check --target $TARGET --features STM32L476VG

after_script: set +e

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
